/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/newModels/waterfall.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[10.95, 0, -0.06]} rotation={[0, 1.57, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials["Waterr.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials["Waterr.009"]}
        />
      </group>
      <group position={[0, 0.82, 0]} rotation={[0, 0.79, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stylized_rock_70002.geometry}
          material={materials.Rocks_}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stylized_rock_70002_1.geometry}
          material={materials["Waterr.006"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/newModels/waterfall.glb");
